### ISSUE TITLE
Sync no longer working

### ISSUE THREAD

**Issue by rjmayott** [macor161/atom-package-sync#15]
Upon trying to add another laptop, I get this error:

Uncaught (in promise) TypeError: Cannot read property 'content' of undefined
    at fetchChanges.then.then.settings (C:\Users\username\.atom\packages\atom-package-sync\lib\get-sync-changes.js:52:78)

None of my devices stay in sync anymore

**Comment by macor161** [comment]
Sorry, due to the increase in popularity of alternative open source IDEs such as VSCode, atom-package-sync has been deprecated.
