### ISSUE TITLE
Google not allowed to login via CEF insecure

### ISSUE THREAD

**Issue by Orlandoech** [macor161/atom-package-sync#19]
Adding lines to .atom\packages\atom-package-sync\lib\quantal-api.js

'disable-web-security': true,
'allowRunningInsecureContent': true
'allow-Running-Insecure-Content': true

DO NOT resolve the issue. Please advise asap.

**Comment by ekazda** [comment]
Any word on this issue? Is this plugin no longer being supported, because this bug is a critical error.

**Comment by robert-cronin** [comment]
same issue

**Comment by Ethanwolfie** [comment]
I know nothing about javascript and electron. I followed what the developer suggested and changed
```javascript 
win.loadURL(`${this._apiUrl}/authentication/app`)
```
 in .atom\packages\atom-package-sync\lib\quantal-api.js to 
```javascript
win.loadURL(`${this._apiUrl}/authentication/app`, {userAgent: 'Chrome'})
```
, but it didn't work. Then I looked  up userAgent in [here](https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome) and changed the line to 
```javascript
win.loadURL(`${this._apiUrl}/authentication/app`, {userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'})
``` 
and it worked. The userAgent may differ on your computer. I hope this helps.

**Comment by ghost** [comment]
yeah, the same problem, google suggest developers use another way, and they have a tutorial about it./

**Comment by gokay05** [comment]
> 
> 
> I know nothing about javascript and electron. I followed what the developer suggested and changed
> 
> ```js
> win.loadURL(`${this._apiUrl}/authentication/app`)
> ```
> 
> in .atom\packages\atom-package-sync\lib\quantal-api.js to
> 
> ```js
> win.loadURL(`${this._apiUrl}/authentication/app`, {userAgent: 'Chrome'})
> ```
> 
> , but it didn't work. Then I looked up userAgent in [here](https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome) and changed the line to
> 
> ```js
> win.loadURL(`${this._apiUrl}/authentication/app`, {userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'})
> ```
> 
> and it worked. The userAgent may differ on your computer. I hope this helps.

This worked for me too. You should grab your browser's user agent from https://www.whatismybrowser.com/guides/the-latest-user-agent and add it to the line Ethan updated.

**Comment by macor161** [comment]
Sorry, due to the increase in popularity of alternative open source IDEs such as VSCode, atom-package-sync has been deprecated.
