### ISSUE TITLE
snippets not synced?

### ISSUE THREAD

**Issue by soniakarkar** [macor161/atom-package-sync#2]
My snippets.cson file doesn't seem to be synced, while the Sync Settings checkbox is checked.
I get the "Packages synced successfully" popup at start up of atom. 
Is there also a "setting synced successfully" pop up that I'm not getting?
I was expecting the snippets to be synced because that the case with the sync-settings package.

**Comment by macor161** [comment]
Thanks for creating this issue. Indeed, there seems to be a problem with the synchronization of the snippets.cson file. I'll try to publish a fix this weekend. In the meantime, I suggest you backup your file to prevent any loss.

**Comment by macor161** [comment]
The bug should be fixed in version 0.2.5
Please make sure to **backup your snippets.cson file** before updating the package.
Let me know if you're still experiencing any problem.
Thanks again for creating the issue.

**Comment by soniakarkar** [comment]
Seems to work ok now.
Thanks for the quick fix! 
And thanks for the package!
