### ISSUE TITLE
Exclude fonts

### ISSUE THREAD

**Issue by lumotroph** [macor161/atom-package-sync#4]
Would be nice if we could have an option to exclude fonts specified in the stylesheet!

**Comment by macor161** [comment]
Hi lumotroph!
I'm not sure I understand your request correctly.  Can you explain a little bit more? You have custom stylesheets but want to exclude the fonts in it?

**Comment by lumotroph** [comment]
Greetings!

Quite the opposite in fact: I have some paid fonts on my development
machine at work, but lack them on my machine at home - so synchronisation
applies a missing font to the text editor on my home machine, given that
the font is specified in my stylesheet.

**Comment by macor161** [comment]
Interresting! Can you give me a sample of the stylesheet you're using? I'll see what I can do.

**Comment by macor161** [comment]
I'm closing this since there is not enough information available.
