### ISSUE TITLE
Blank Google login page on Ubuntu

### ISSUE THREAD

**Issue by robpneu** [macor161/atom-package-sync#5]
I've been using your package sync package 2 macs for a while now and it's been great!

I just got it installed on my Ubuntu 16.04 Virtual machine but when I launch Atom, the google login popup (at least I think that's what it is) just comes up blank. Any ideas?

![screenshot from 2018-03-05 09-18-33](https://user-images.githubusercontent.com/10223171/36986110-3cb27432-2056-11e8-8a84-60fb01b99337.png)

**Comment by macor161** [comment]
Hi Rob! Thanks for creating this issue. I'm going to check this out tomorrow and get back to you as soon as I have more news about this.

**Comment by xoppyk** [comment]
Mac OS 10.12.06 some...

**Comment by macor161** [comment]
Turns out that the load balancer was down. Is it working for you now?

**Comment by xoppyk** [comment]
Now all fine, its work !!! xD Thanks !!!!!

**Comment by macor161** [comment]
Great! Thanks @robpneu and @xoppyk for your feedback, it's very much appreciated!
Let me know if there are still problems on Ubuntu or another OS and I'll reopen the issue.

**Comment by chipgw** [comment]
I'm currently having this issue. (I'm on Archlinux if that matters. EDIT: Also a problem on Windows 10)

**Comment by macor161** [comment]
Hi @chipgw , it should be fixed now. The server was down again.

**Comment by gign0766** [comment]
Hi, I'm also having this issue on Windows 10, today

**Comment by helispot** [comment]
Having the issue today.  Ubuntu 18.04.  Atom 1.33.1.

**Comment by Vagrantin** [comment]
Hello I'm also having the issue today.
I guess you have again the server down ?
Are thinking about  a stable solution ? Does providing a backup server would help ?
Thanks

**Comment by SenDesignRO** [comment]
Issue also present on MacOS 10.14.3.

**Comment by officiallyemma** [comment]
I'm running into this issue right now on Ubuntu. I'm running v1.56.0 of atom and v0.4.0 of atom-package-sync.

The console shows the following error

```
Uncaught (in promise) Error: ERR_CONNECTION_TIMED_OUT (-118) loading 'https://api.atom-package-sync.com/authentication/app'
```
