### ISSUE TITLE
Change Google account used for sync

### ISSUE THREAD

**Issue by montewebster** [macor161/atom-package-sync#6]
Hello,
This is a great package. I am using it to sync between machines with Linux and Windows. It works great. 

I was wondering how I could reset my google info, so I could switch to a different account to do the sync.  I have tried uninstall/install and looking for config info in various atom directories, but I can't find a way to trigger this re-setup on the account info. 

Thanks

**Comment by DaniWinter** [comment]
I'd also like to know this.

**Comment by th23x** [comment]
Indeed...looking for the same info - no iead how/ where to change my account settings

**Comment by TheBeardedB** [comment]
I just added a pull-req that adds a logout functionality. In the mean time you can get a package [local-storage](https://atom.io/packages/local-storage) that will let you remove the stored keys.

You need to remove:
atom-package-sync:googleToken
atom-package-sync:quantalToken

**Comment by macor161** [comment]
Thanks @TheBeardedB for the pull request. I will try to review this tomorrow and have an update ready by the end of the week.

**Comment by macor161** [comment]
The new feature is now released. You can log out with the following command:
```
atom-package-sync:logout
```

Huge thanks to @TheBeardedB for the pull request.
