### ISSUE TITLE
Blank window instead of showing loggin to Google

### ISSUE THREAD

**Issue by MCXDeveloper** [macor161/atom-package-sync#7]
I have used this package before and now that I bought a new PC I installed atom and install this package to sync my packages and config files but I got the issue that a blank window shows (actually this window show the loggin with Google) and I dont know what could it be... Any help?

Here's the link with a screenshot of the blank window. (https://ibb.co/hEj96e)

Thanks in advance!

**Comment by macor161** [comment]
Thanks for submiting the issue @MCXDeveloper . This should be fixed in about an hour.

**Comment by macor161** [comment]
The issue should be solved. Thanks again for reporting the problem!

**Comment by macor161** [comment]
Don't hesitate to comment again here if you are still experiencing trouble with the package and I'll open back the issue.

**Comment by azuryst** [comment]
I am experiencing the same issue.

**Comment by MCXDeveloper** [comment]
Thanks for your reply @macor161 .  The issue still happens.

**Comment by macor161** [comment]
@azuryst @MCXDeveloper It should be fixed by now. Google Cloud Platform doesn't seem really stable. I'm considering switching to AWS. Thanks for reporting this issue, really appreciated!

**Comment by gign0766** [comment]
Hi, I'm also having this issue on Windows 10

**Comment by seantma** [comment]
@macor161 Thanks for fixing it previously, but the issue seems to come back, specifically on Windows 10 as there's just a blank screen.

![capture](https://user-images.githubusercontent.com/915443/50903079-b3b88480-13ea-11e9-8136-4e5da25740ee.PNG)

**Comment by arnoldmanzano** [comment]
Also got this on a recent install on OS X. Seemed to work on 2 previous Windows machines though.

**Comment by eagl3s1ght** [comment]
I have this problem as well.

> Don't hesitate to comment again here if you are still experiencing trouble with the package and I'll open back the issue.

**Comment by gign0766** [comment]
I still have this issue as well !

There is a blank screen at each Atom launch

![image](https://user-images.githubusercontent.com/15085503/51911545-6a000000-23d2-11e9-816c-f1bf3c646a1f.png)

**Comment by SenDesignRO** [comment]
Same problem with MacOS 10.14.3.

**Comment by rfreitas** [comment]
Same problem on MacOS 10.14.3 atom 1.34.0

**Comment by MCXDeveloper** [comment]
Just today I went back to using Atom again and only waited a few seconds and the login with Google appeared in the normal way.  You can test it now I guess.

**Comment by github-sjacobs** [comment]
Just now I was able to use this package on my Mac with fully configured Atom and it seems to have worked and uploaded everything fine. Trying to load settings to a new installation on a new Win 10 laptop I have seen both a mostly blank window with text at the top "Atom Package Sync Authentication" and the one with all the menus.

Atom 1.39.1
atom-package-sync 0.4.0

**Comment by pablisch** [comment]
Hello, I get the same issue, a blank popup window with **atom** in the title bar. It happens on a Mac Pro running OSX 10.14.6 and a MacBook Air running OSX 10.15.7
