### ISSUE TITLE
Packages and Settings not syncing

### ISSUE THREAD

**Issue by anthonyekosky** [macor161/atom-package-sync#8]
My packages and settings are not syncing.
I've updated my atom IDE and packages, but it's not syncing.
I've also tried to uninstall and reinstall this package and it's still not working.

This is unfortunate because this package was awesome.

**Comment by lkev** [comment]
+1 -  came across this package, but when I go to install it, I'm not given the option to sign in. Instead, a blank white atom window pops up after installation:

![image](https://user-images.githubusercontent.com/3269734/51906602-62356100-23bc-11e9-8c29-ca2c57c4d724.png)

**Comment by metafaniel** [comment]
HI!
I also have the same problem as @lkev mentioned above in _Windows 10_.
a) I tried changing system default web browser and restarted Atom every time.... if that had something to do I thought but nope =P
b) I disabled all other Community Packages I have and restarted Atom to no avail. The difference is the blank screen does not load any menu items this way.
c) Ticking and unticking the few options available: same behavior as before.
d) Opening the Atom WebTools it shows nothing about the package until the blank window is closed:

![image](https://user-images.githubusercontent.com/2229174/52141449-68754880-261b-11e9-82c4-cc66681f85c0.png)

Maybe this is useful for something.
Greetings and I hope to get an update to _try_ the package.

Thanks.

**Comment by Salamafet** [comment]
Apparently the server "atom-package-sync.com" doesn't serve web service anymore.
After a rapid port scan, only ssh are active on the server.

Is the project abandoned ?

**Comment by anthonyekosky** [comment]
I've since switched over the to the apm star and install star method.
No reason to have this package anymore.

**Comment by macor161** [comment]
Terribly sorry for the delay. I had a look at the server today and should be able to fix the problem tomorrow.

**Comment by macor161** [comment]
It is taking a bit more time than expected, I have to upgrade the server. It should be back online by Monday.

**Comment by ghstridr** [comment]
> Apparently the server "atom-package-sync.com" doesn't serve web service anymore.
> After a rapid port scan, only ssh are active on the server.
> 
> Is the project abandoned ?

Next time, just 'let yourself in' and restart the web service. ;-)

**Comment by anthonyekosky** [comment]
Changed to another solution.

**Comment by macor161** [comment]
Sorry again for the delay. The service should be back up

**Comment by andercodder** [comment]
sorry but my settings an packages are not sync..i dont know why it asked me for the f«google account i put it well no errors but it does not sync

**Comment by metafaniel** [comment]
> Changed to another solution.

Can you please share your discovery? It may be useful, thanks.
